apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  labels:
    app: fastapi-board
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: fastapi-board
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fastapi-board
    spec:
      containers:
        - name: fastapi-container
          image: enohs/fastapi-board:46e4210c9659154d5cb9a4e65ed059d1b8f71cdf
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_HOST
              value: "10.0.2.4"
            - name: POSTGRES_DB
              value: "cloudnative"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "mysecretpassword"
